#include <string.h>
#include <linux/uinput.h>

#include "keys.h"

/**
 * Converts a key string (e.g. "KEY_I") to its corresponding code.
 * */
int convertKeyStringToCode(char* keyString)
{
    if (NULL == keyString) return 0;
    else if (strcmp(keyString, "KEY_ESC") == 0) return KEY_ESC;
    else if (strcmp(keyString, "ESC") == 0)     return KEY_ESC;
    else if (!strcmp(keyString, "KEY_1") return KEY_1;
    else if (!strcmp(keyString, "1"    ) return KEY_1;
    else if (!strcmp(keyString, "KEY_2") return KEY_2;
    else if (!strcmp(keyString, "2"    ) return KEY_2;
    else if (!strcmp(keyString, "KEY_3") return KEY_3;
    else if (!strcmp(keyString, "3"    ) return KEY_3;
    else if (!strcmp(keyString, "KEY_4") return KEY_4;
    else if (!strcmp(keyString, "4"    ) return KEY_4;
    else if (!strcmp(keyString, "KEY_5") return KEY_5;
    else if (!strcmp(keyString, "5"    ) return KEY_5;
    else if (!strcmp(keyString, "KEY_6") return KEY_6;
    else if (!strcmp(keyString, "6"    ) return KEY_6;
    else if (!strcmp(keyString, "KEY_7") return KEY_7;
    else if (!strcmp(keyString, "7"    ) return KEY_7;
    else if (!strcmp(keyString, "KEY_8") return KEY_8;
    else if (!strcmp(keyString, "8"    ) return KEY_8;
    else if (!strcmp(keyString, "KEY_9") return KEY_9;
    else if (!strcmp(keyString, "9"    ) return KEY_9;
    else if (!strcmp(keyString, "KEY_0") return KEY_0;
    else if (!strcmp(keyString, "0"    ) return KEY_0;
    else if (!strcmp(keyString, "KEY_MINUS") return KEY_MINUS;
    else if (!strcmp(keyString, "MINUS"    ) return KEY_MINUS;
    else if (!strcmp(keyString, "KEY_EQUAL") return KEY_EQUAL;
    else if (!strcmp(keyString, "EQUAL"    ) return KEY_EQUAL;
    else if (!strcmp(keyString, "KEY_BACKSPACE") return KEY_BACKSPACE;
    else if (!strcmp(keyString, "BACKSPACE"    ) return KEY_BACKSPACE;
    else if (!strcmp(keyString, "KEY_TAB") return KEY_TAB;
    else if (!strcmp(keyString, "TAB"    ) return KEY_TAB;
    else if (!strcmp(keyString, "KEY_Q") return KEY_Q;
    else if (!strcmp(keyString, "Q"    ) return KEY_Q;
    else if (!strcmp(keyString, "KEY_W") return KEY_W;
    else if (!strcmp(keyString, "W"    ) return KEY_W;
    else if (!strcmp(keyString, "KEY_E") return KEY_E;
    else if (!strcmp(keyString, "E"    ) return KEY_E;
    else if (!strcmp(keyString, "KEY_R") return KEY_R;
    else if (!strcmp(keyString, "R"    ) return KEY_R;
    else if (!strcmp(keyString, "KEY_T") return KEY_T;
    else if (!strcmp(keyString, "T"    ) return KEY_T;
    else if (!strcmp(keyString, "KEY_Y") return KEY_Y;
    else if (!strcmp(keyString, "Y"    ) return KEY_Y;
    else if (!strcmp(keyString, "KEY_U") return KEY_U;
    else if (!strcmp(keyString, "U"    ) return KEY_U;
    else if (!strcmp(keyString, "KEY_I") return KEY_I;
    else if (!strcmp(keyString, "I"    ) return KEY_I;
    else if (!strcmp(keyString, "KEY_O") return KEY_O;
    else if (!strcmp(keyString, "O"    ) return KEY_O;
    else if (!strcmp(keyString, "KEY_P") return KEY_P;
    else if (!strcmp(keyString, "P"    ) return KEY_P;
    else if (!strcmp(keyString, "KEY_LEFTBRACE") return KEY_LEFTBRACE;
    else if (!strcmp(keyString, "LEFTBRACE"    ) return KEY_LEFTBRACE;
    else if (!strcmp(keyString, "KEY_RIGHTBRACE") return KEY_RIGHTBRACE;
    else if (!strcmp(keyString, "RIGHTBRACE"    ) return KEY_RIGHTBRACE;
    else if (!strcmp(keyString, "KEY_ENTER") return KEY_ENTER;
    else if (!strcmp(keyString, "ENTER"    ) return KEY_ENTER;
    else if (!strcmp(keyString, "KEY_LEFTCTRL") return KEY_LEFTCTRL;
    else if (!strcmp(keyString, "LEFTCTRL"    ) return KEY_LEFTCTRL;
    else if (!strcmp(keyString, "KEY_A") return KEY_A;
    else if (!strcmp(keyString, "A"    ) return KEY_A;
    else if (!strcmp(keyString, "KEY_S") return KEY_S;
    else if (!strcmp(keyString, "S"    ) return KEY_S;
    else if (!strcmp(keyString, "KEY_D") return KEY_D;
    else if (!strcmp(keyString, "D"    ) return KEY_D;
    else if (!strcmp(keyString, "KEY_F") return KEY_F;
    else if (!strcmp(keyString, "F"    ) return KEY_F;
    else if (!strcmp(keyString, "KEY_G") return KEY_G;
    else if (!strcmp(keyString, "G"    ) return KEY_G;
    else if (!strcmp(keyString, "KEY_H") return KEY_H;
    else if (!strcmp(keyString, "H"    ) return KEY_H;
    else if (!strcmp(keyString, "KEY_J") return KEY_J;
    else if (!strcmp(keyString, "J"    ) return KEY_J;
    else if (!strcmp(keyString, "KEY_K") return KEY_K;
    else if (!strcmp(keyString, "K"    ) return KEY_K;
    else if (!strcmp(keyString, "KEY_L") return KEY_L;
    else if (!strcmp(keyString, "L"    ) return KEY_L;
    else if (!strcmp(keyString, "KEY_SEMICOLON") return KEY_SEMICOLON;
    else if (!strcmp(keyString, "SEMICOLON"    ) return KEY_SEMICOLON;
    else if (!strcmp(keyString, "KEY_APOSTROPHE") return KEY_APOSTROPHE;
    else if (!strcmp(keyString, "APOSTROPHE"    ) return KEY_APOSTROPHE;
    else if (!strcmp(keyString, "KEY_GRAVE") return KEY_GRAVE;
    else if (!strcmp(keyString, "GRAVE"    ) return KEY_GRAVE;
    else if (!strcmp(keyString, "KEY_LEFTSHIFT") return KEY_LEFTSHIFT;
    else if (!strcmp(keyString, "LEFTSHIFT"    ) return KEY_LEFTSHIFT;
    else if (!strcmp(keyString, "KEY_BACKSLASH") return KEY_BACKSLASH;
    else if (!strcmp(keyString, "BACKSLASH"    ) return KEY_BACKSLASH;
    else if (!strcmp(keyString, "KEY_Z") return KEY_Z;
    else if (!strcmp(keyString, "Z"    ) return KEY_Z;
    else if (!strcmp(keyString, "KEY_X") return KEY_X;
    else if (!strcmp(keyString, "X"    ) return KEY_X;
    else if (!strcmp(keyString, "KEY_C") return KEY_C;
    else if (!strcmp(keyString, "C"    ) return KEY_C;
    else if (!strcmp(keyString, "KEY_V") return KEY_V;
    else if (!strcmp(keyString, "V"    ) return KEY_V;
    else if (!strcmp(keyString, "KEY_B") return KEY_B;
    else if (!strcmp(keyString, "B"    ) return KEY_B;
    else if (!strcmp(keyString, "KEY_N") return KEY_N;
    else if (!strcmp(keyString, "N"    ) return KEY_N;
    else if (!strcmp(keyString, "KEY_M") return KEY_M;
    else if (!strcmp(keyString, "M"    ) return KEY_M;
    else if (!strcmp(keyString, "KEY_COMMA") return KEY_COMMA;
    else if (!strcmp(keyString, "COMMA"    ) return KEY_COMMA;
    else if (!strcmp(keyString, "KEY_DOT") return KEY_DOT;
    else if (!strcmp(keyString, "DOT"    ) return KEY_DOT;
    else if (!strcmp(keyString, "KEY_SLASH") return KEY_SLASH;
    else if (!strcmp(keyString, "SLASH"    ) return KEY_SLASH;
    else if (!strcmp(keyString, "KEY_RIGHTSHIFT") return KEY_RIGHTSHIFT;
    else if (!strcmp(keyString, "RIGHTSHIFT"    ) return KEY_RIGHTSHIFT;
    else if (!strcmp(keyString, "KEY_KPASTERISK") return KEY_KPASTERISK;
    else if (!strcmp(keyString, "KPASTERISK"    ) return KEY_KPASTERISK;
    else if (!strcmp(keyString, "KEY_LEFTALT") return KEY_LEFTALT;
    else if (!strcmp(keyString, "LEFTALT"    ) return KEY_LEFTALT;
    else if (!strcmp(keyString, "KEY_SPACE") return KEY_SPACE;
    else if (!strcmp(keyString, "SPACE"    ) return KEY_SPACE;
    else if (!strcmp(keyString, "KEY_CAPSLOCK") return KEY_CAPSLOCK;
    else if (!strcmp(keyString, "CAPSLOCK"    ) return KEY_CAPSLOCK;
    else if (!strcmp(keyString, "KEY_F1") return KEY_F1;
    else if (!strcmp(keyString, "F1"    ) return KEY_F1;
    else if (!strcmp(keyString, "KEY_F2") return KEY_F2;
    else if (!strcmp(keyString, "F2"    ) return KEY_F2;
    else if (!strcmp(keyString, "KEY_F3") return KEY_F3;
    else if (!strcmp(keyString, "F3"    ) return KEY_F3;
    else if (!strcmp(keyString, "KEY_F4") return KEY_F4;
    else if (!strcmp(keyString, "F4"    ) return KEY_F4;
    else if (!strcmp(keyString, "KEY_F5") return KEY_F5;
    else if (!strcmp(keyString, "F5"    ) return KEY_F5;
    else if (!strcmp(keyString, "KEY_F6") return KEY_F6;
    else if (!strcmp(keyString, "F6"    ) return KEY_F6;
    else if (!strcmp(keyString, "KEY_F7") return KEY_F7;
    else if (!strcmp(keyString, "F7"    ) return KEY_F7;
    else if (!strcmp(keyString, "KEY_F8") return KEY_F8;
    else if (!strcmp(keyString, "F8"    ) return KEY_F8;
    else if (!strcmp(keyString, "KEY_F9") return KEY_F9;
    else if (!strcmp(keyString, "F9"    ) return KEY_F9;
    else if (!strcmp(keyString, "KEY_F10") return KEY_F10;
    else if (!strcmp(keyString, "F10"    ) return KEY_F10;
    else if (!strcmp(keyString, "KEY_NUMLOCK") return KEY_NUMLOCK;
    else if (!strcmp(keyString, "NUMLOCK"    ) return KEY_NUMLOCK;
    else if (!strcmp(keyString, "KEY_SCROLLLOCK") return KEY_SCROLLLOCK;
    else if (!strcmp(keyString, "SCROLLLOCK"    ) return KEY_SCROLLLOCK;
    else if (!strcmp(keyString, "KEY_KP7") return KEY_KP7;
    else if (!strcmp(keyString, "KP7"    ) return KEY_KP7;
    else if (!strcmp(keyString, "KEY_KP8") return KEY_KP8;
    else if (!strcmp(keyString, "KP8"    ) return KEY_KP8;
    else if (!strcmp(keyString, "KEY_KP9") return KEY_KP9;
    else if (!strcmp(keyString, "KP9"    ) return KEY_KP9;
    else if (!strcmp(keyString, "KEY_KPMINUS") return KEY_KPMINUS;
    else if (!strcmp(keyString, "KPMINUS"    ) return KEY_KPMINUS;
    else if (!strcmp(keyString, "KEY_KP4") return KEY_KP4;
    else if (!strcmp(keyString, "KP4"    ) return KEY_KP4;
    else if (!strcmp(keyString, "KEY_KP5") return KEY_KP5;
    else if (!strcmp(keyString, "KP5"    ) return KEY_KP5;
    else if (!strcmp(keyString, "KEY_KP6") return KEY_KP6;
    else if (!strcmp(keyString, "KP6"    ) return KEY_KP6;
    else if (!strcmp(keyString, "KEY_KPPLUS") return KEY_KPPLUS;
    else if (!strcmp(keyString, "KPPLUS"    ) return KEY_KPPLUS;
    else if (!strcmp(keyString, "KEY_KP1") return KEY_KP1;
    else if (!strcmp(keyString, "KP1"    ) return KEY_KP1;
    else if (!strcmp(keyString, "KEY_KP2") return KEY_KP2;
    else if (!strcmp(keyString, "KP2"    ) return KEY_KP2;
    else if (!strcmp(keyString, "KEY_KP3") return KEY_KP3;
    else if (!strcmp(keyString, "KP3"    ) return KEY_KP3;
    else if (!strcmp(keyString, "KEY_KP0") return KEY_KP0;
    else if (!strcmp(keyString, "KP0"    ) return KEY_KP0;
    else if (!strcmp(keyString, "KEY_KPDOT") return KEY_KPDOT;
    else if (!strcmp(keyString, "KPDOT"    ) return KEY_KPDOT;
    else if (!strcmp(keyString, "KEY_ZENKAKUHANKAKU") return KEY_ZENKAKUHANKAKU;
    else if (!strcmp(keyString, "ZENKAKUHANKAKU"    ) return KEY_ZENKAKUHANKAKU;
    else if (!strcmp(keyString, "KEY_102ND") return KEY_102ND;
    else if (!strcmp(keyString, "102ND"    ) return KEY_102ND;
    else if (!strcmp(keyString, "KEY_F11") return KEY_F11;
    else if (!strcmp(keyString, "F11"    ) return KEY_F11;
    else if (!strcmp(keyString, "KEY_F12") return KEY_F12;
    else if (!strcmp(keyString, "F12"    ) return KEY_F12;
    else if (!strcmp(keyString, "KEY_RO") return KEY_RO;
    else if (!strcmp(keyString, "RO"    ) return KEY_RO;
    else if (!strcmp(keyString, "KEY_KATAKANA") return KEY_KATAKANA;
    else if (!strcmp(keyString, "KATAKANA"    ) return KEY_KATAKANA;
    else if (!strcmp(keyString, "KEY_HIRAGANA") return KEY_HIRAGANA;
    else if (!strcmp(keyString, "HIRAGANA"    ) return KEY_HIRAGANA;
    else if (!strcmp(keyString, "KEY_HENKAN") return KEY_HENKAN;
    else if (!strcmp(keyString, "HENKAN"    ) return KEY_HENKAN;
    else if (!strcmp(keyString, "KEY_KATAKANAHIRAGANA") return KEY_KATAKANAHIRAGANA;
    else if (!strcmp(keyString, "KATAKANAHIRAGANA"    ) return KEY_KATAKANAHIRAGANA;
    else if (!strcmp(keyString, "KEY_MUHENKAN") return KEY_MUHENKAN;
    else if (!strcmp(keyString, "MUHENKAN"    ) return KEY_MUHENKAN;
    else if (!strcmp(keyString, "KEY_KPJPCOMMA") return KEY_KPJPCOMMA;
    else if (!strcmp(keyString, "KPJPCOMMA"    ) return KEY_KPJPCOMMA;
    else if (!strcmp(keyString, "KEY_KPENTER") return KEY_KPENTER;
    else if (!strcmp(keyString, "KPENTER"    ) return KEY_KPENTER;
    else if (!strcmp(keyString, "KEY_RIGHTCTRL") return KEY_RIGHTCTRL;
    else if (!strcmp(keyString, "RIGHTCTRL"    ) return KEY_RIGHTCTRL;
    else if (!strcmp(keyString, "KEY_KPSLASH") return KEY_KPSLASH;
    else if (!strcmp(keyString, "KPSLASH"    ) return KEY_KPSLASH;
    else if (!strcmp(keyString, "KEY_SYSRQ") return KEY_SYSRQ;
    else if (!strcmp(keyString, "SYSRQ"    ) return KEY_SYSRQ;
    else if (!strcmp(keyString, "KEY_RIGHTALT") return KEY_RIGHTALT;
    else if (!strcmp(keyString, "RIGHTALT"    ) return KEY_RIGHTALT;
    else if (!strcmp(keyString, "KEY_LINEFEED") return KEY_LINEFEED;
    else if (!strcmp(keyString, "LINEFEED"    ) return KEY_LINEFEED;
    else if (!strcmp(keyString, "KEY_HOME") return KEY_HOME;
    else if (!strcmp(keyString, "HOME"    ) return KEY_HOME;
    else if (!strcmp(keyString, "KEY_UP") return KEY_UP;
    else if (!strcmp(keyString, "UP"    ) return KEY_UP;
    else if (!strcmp(keyString, "KEY_PAGEUP") return KEY_PAGEUP;
    else if (!strcmp(keyString, "PAGEUP"    ) return KEY_PAGEUP;
    else if (!strcmp(keyString, "KEY_LEFT") return KEY_LEFT;
    else if (!strcmp(keyString, "LEFT"    ) return KEY_LEFT;
    else if (!strcmp(keyString, "KEY_RIGHT") return KEY_RIGHT;
    else if (!strcmp(keyString, "RIGHT"    ) return KEY_RIGHT;
    else if (!strcmp(keyString, "KEY_END") return KEY_END;
    else if (!strcmp(keyString, "END"    ) return KEY_END;
    else if (!strcmp(keyString, "KEY_DOWN") return KEY_DOWN;
    else if (!strcmp(keyString, "DOWN"    ) return KEY_DOWN;
    else if (!strcmp(keyString, "KEY_PAGEDOWN") return KEY_PAGEDOWN;
    else if (!strcmp(keyString, "PAGEDOWN"    ) return KEY_PAGEDOWN;
    else if (!strcmp(keyString, "KEY_INSERT") return KEY_INSERT;
    else if (!strcmp(keyString, "INSERT"    ) return KEY_INSERT;
    else if (!strcmp(keyString, "KEY_DELETE") return KEY_DELETE;
    else if (!strcmp(keyString, "DELETE"    ) return KEY_DELETE;
    else if (!strcmp(keyString, "KEY_MACRO") return KEY_MACRO;
    else if (!strcmp(keyString, "MACRO"    ) return KEY_MACRO;
    else if (!strcmp(keyString, "KEY_MUTE") return KEY_MUTE;
    else if (!strcmp(keyString, "MUTE"    ) return KEY_MUTE;
    else if (!strcmp(keyString, "KEY_VOLUMEDOWN") return KEY_VOLUMEDOWN;
    else if (!strcmp(keyString, "VOLUMEDOWN"    ) return KEY_VOLUMEDOWN;
    else if (!strcmp(keyString, "KEY_VOLUMEUP") return KEY_VOLUMEUP;
    else if (!strcmp(keyString, "VOLUMEUP"    ) return KEY_VOLUMEUP;
    else if (!strcmp(keyString, "KEY_POWER") return KEY_POWER;
    else if (!strcmp(keyString, "POWER"    ) return KEY_POWER;
    else if (!strcmp(keyString, "KEY_KPEQUAL") return KEY_KPEQUAL;
    else if (!strcmp(keyString, "KPEQUAL"    ) return KEY_KPEQUAL;
    else if (!strcmp(keyString, "KEY_KPPLUSMINUS") return KEY_KPPLUSMINUS;
    else if (!strcmp(keyString, "KPPLUSMINUS"    ) return KEY_KPPLUSMINUS;
    else if (!strcmp(keyString, "KEY_PAUSE") return KEY_PAUSE;
    else if (!strcmp(keyString, "PAUSE"    ) return KEY_PAUSE;
    else if (!strcmp(keyString, "KEY_SCALE") return KEY_SCALE;
    else if (!strcmp(keyString, "SCALE"    ) return KEY_SCALE;
    else if (!strcmp(keyString, "KEY_KPCOMMA") return KEY_KPCOMMA;
    else if (!strcmp(keyString, "KPCOMMA"    ) return KEY_KPCOMMA;
    else if (!strcmp(keyString, "KEY_HANGEUL") return KEY_HANGEUL;
    else if (!strcmp(keyString, "HANGEUL"    ) return KEY_HANGEUL;
    else if (!strcmp(keyString, "KEY_HANGUEL") return KEY_HANGUEL;
    else if (!strcmp(keyString, "HANGUEL"    ) return KEY_HANGUEL;
    else if (!strcmp(keyString, "KEY_HANJA") return KEY_HANJA;
    else if (!strcmp(keyString, "HANJA"    ) return KEY_HANJA;
    else if (!strcmp(keyString, "KEY_YEN") return KEY_YEN;
    else if (!strcmp(keyString, "YEN"    ) return KEY_YEN;
    else if (!strcmp(keyString, "KEY_LEFTMETA") return KEY_LEFTMETA;
    else if (!strcmp(keyString, "LEFTMETA"    ) return KEY_LEFTMETA;
    else if (!strcmp(keyString, "KEY_RIGHTMETA") return KEY_RIGHTMETA;
    else if (!strcmp(keyString, "RIGHTMETA"    ) return KEY_RIGHTMETA;
    else if (!strcmp(keyString, "KEY_COMPOSE") return KEY_COMPOSE;
    else if (!strcmp(keyString, "COMPOSE"    ) return KEY_COMPOSE;
    else if (!strcmp(keyString, "KEY_STOP") return KEY_STOP;
    else if (!strcmp(keyString, "STOP"    ) return KEY_STOP;
    else if (!strcmp(keyString, "KEY_AGAIN") return KEY_AGAIN;
    else if (!strcmp(keyString, "AGAIN"    ) return KEY_AGAIN;
    else if (!strcmp(keyString, "KEY_PROPS") return KEY_PROPS;
    else if (!strcmp(keyString, "PROPS"    ) return KEY_PROPS;
    else if (!strcmp(keyString, "KEY_UNDO") return KEY_UNDO;
    else if (!strcmp(keyString, "UNDO"    ) return KEY_UNDO;
    else if (!strcmp(keyString, "KEY_FRONT") return KEY_FRONT;
    else if (!strcmp(keyString, "FRONT"    ) return KEY_FRONT;
    else if (!strcmp(keyString, "KEY_COPY") return KEY_COPY;
    else if (!strcmp(keyString, "COPY"    ) return KEY_COPY;
    else if (!strcmp(keyString, "KEY_OPEN") return KEY_OPEN;
    else if (!strcmp(keyString, "OPEN"    ) return KEY_OPEN;
    else if (!strcmp(keyString, "KEY_PASTE") return KEY_PASTE;
    else if (!strcmp(keyString, "PASTE"    ) return KEY_PASTE;
    else if (!strcmp(keyString, "KEY_FIND") return KEY_FIND;
    else if (!strcmp(keyString, "FIND"    ) return KEY_FIND;
    else if (!strcmp(keyString, "KEY_CUT") return KEY_CUT;
    else if (!strcmp(keyString, "CUT"    ) return KEY_CUT;
    else if (!strcmp(keyString, "KEY_HELP") return KEY_HELP;
    else if (!strcmp(keyString, "HELP"    ) return KEY_HELP;
    else if (!strcmp(keyString, "KEY_MENU") return KEY_MENU;
    else if (!strcmp(keyString, "MENU"    ) return KEY_MENU;
    else if (!strcmp(keyString, "KEY_CALC") return KEY_CALC;
    else if (!strcmp(keyString, "CALC"    ) return KEY_CALC;
    else if (!strcmp(keyString, "KEY_SETUP") return KEY_SETUP;
    else if (!strcmp(keyString, "SETUP"    ) return KEY_SETUP;
    else if (!strcmp(keyString, "KEY_SLEEP") return KEY_SLEEP;
    else if (!strcmp(keyString, "SLEEP"    ) return KEY_SLEEP;
    else if (!strcmp(keyString, "KEY_WAKEUP") return KEY_WAKEUP;
    else if (!strcmp(keyString, "WAKEUP"    ) return KEY_WAKEUP;
    else if (!strcmp(keyString, "KEY_FILE") return KEY_FILE;
    else if (!strcmp(keyString, "FILE"    ) return KEY_FILE;
    else if (!strcmp(keyString, "KEY_SENDFILE") return KEY_SENDFILE;
    else if (!strcmp(keyString, "SENDFILE"    ) return KEY_SENDFILE;
    else if (!strcmp(keyString, "KEY_DELETEFILE") return KEY_DELETEFILE;
    else if (!strcmp(keyString, "DELETEFILE"    ) return KEY_DELETEFILE;
    else if (!strcmp(keyString, "KEY_XFER") return KEY_XFER;
    else if (!strcmp(keyString, "XFER"    ) return KEY_XFER;
    else if (!strcmp(keyString, "KEY_PROG1") return KEY_PROG1;
    else if (!strcmp(keyString, "PROG1"    ) return KEY_PROG1;
    else if (!strcmp(keyString, "KEY_PROG2") return KEY_PROG2;
    else if (!strcmp(keyString, "PROG2"    ) return KEY_PROG2;
    else if (!strcmp(keyString, "KEY_WWW") return KEY_WWW;
    else if (!strcmp(keyString, "WWW"    ) return KEY_WWW;
    else if (!strcmp(keyString, "KEY_MSDOS") return KEY_MSDOS;
    else if (!strcmp(keyString, "MSDOS"    ) return KEY_MSDOS;
    else if (!strcmp(keyString, "KEY_COFFEE") return KEY_COFFEE;
    else if (!strcmp(keyString, "COFFEE"    ) return KEY_COFFEE;
    else if (!strcmp(keyString, "KEY_SCREENLOCK") return KEY_SCREENLOCK;
    else if (!strcmp(keyString, "SCREENLOCK"    ) return KEY_SCREENLOCK;
    else if (!strcmp(keyString, "KEY_ROTATE_DISPLAY") return KEY_ROTATE_DISPLAY;
    else if (!strcmp(keyString, "ROTATE_DISPLAY"    ) return KEY_ROTATE_DISPLAY;
    else if (!strcmp(keyString, "KEY_DIRECTION") return KEY_DIRECTION;
    else if (!strcmp(keyString, "DIRECTION"    ) return KEY_DIRECTION;
    else if (!strcmp(keyString, "KEY_CYCLEWINDOWS") return KEY_CYCLEWINDOWS;
    else if (!strcmp(keyString, "CYCLEWINDOWS"    ) return KEY_CYCLEWINDOWS;
    else if (!strcmp(keyString, "KEY_MAIL") return KEY_MAIL;
    else if (!strcmp(keyString, "MAIL"    ) return KEY_MAIL;
    else if (!strcmp(keyString, "KEY_BOOKMARKS") return KEY_BOOKMARKS;
    else if (!strcmp(keyString, "BOOKMARKS"    ) return KEY_BOOKMARKS;
    else if (!strcmp(keyString, "KEY_COMPUTER") return KEY_COMPUTER;
    else if (!strcmp(keyString, "COMPUTER"    ) return KEY_COMPUTER;
    else if (!strcmp(keyString, "KEY_BACK") return KEY_BACK;
    else if (!strcmp(keyString, "BACK"    ) return KEY_BACK;
    else if (!strcmp(keyString, "KEY_FORWARD") return KEY_FORWARD;
    else if (!strcmp(keyString, "FORWARD"    ) return KEY_FORWARD;
    else if (!strcmp(keyString, "KEY_CLOSECD") return KEY_CLOSECD;
    else if (!strcmp(keyString, "CLOSECD"    ) return KEY_CLOSECD;
    else if (!strcmp(keyString, "KEY_EJECTCD") return KEY_EJECTCD;
    else if (!strcmp(keyString, "EJECTCD"    ) return KEY_EJECTCD;
    else if (!strcmp(keyString, "KEY_EJECTCLOSECD") return KEY_EJECTCLOSECD;
    else if (!strcmp(keyString, "EJECTCLOSECD"    ) return KEY_EJECTCLOSECD;
    else if (!strcmp(keyString, "KEY_NEXTSONG") return KEY_NEXTSONG;
    else if (!strcmp(keyString, "NEXTSONG"    ) return KEY_NEXTSONG;
    else if (!strcmp(keyString, "KEY_PLAYPAUSE") return KEY_PLAYPAUSE;
    else if (!strcmp(keyString, "PLAYPAUSE"    ) return KEY_PLAYPAUSE;
    else if (!strcmp(keyString, "KEY_PREVIOUSSONG") return KEY_PREVIOUSSONG;
    else if (!strcmp(keyString, "PREVIOUSSONG"    ) return KEY_PREVIOUSSONG;
    else if (!strcmp(keyString, "KEY_STOPCD") return KEY_STOPCD;
    else if (!strcmp(keyString, "STOPCD"    ) return KEY_STOPCD;
    else if (!strcmp(keyString, "KEY_RECORD") return KEY_RECORD;
    else if (!strcmp(keyString, "RECORD"    ) return KEY_RECORD;
    else if (!strcmp(keyString, "KEY_REWIND") return KEY_REWIND;
    else if (!strcmp(keyString, "REWIND"    ) return KEY_REWIND;
    else if (!strcmp(keyString, "KEY_PHONE") return KEY_PHONE;
    else if (!strcmp(keyString, "PHONE"    ) return KEY_PHONE;
    else if (!strcmp(keyString, "KEY_ISO") return KEY_ISO;
    else if (!strcmp(keyString, "ISO"    ) return KEY_ISO;
    else if (!strcmp(keyString, "KEY_CONFIG") return KEY_CONFIG;
    else if (!strcmp(keyString, "CONFIG"    ) return KEY_CONFIG;
    else if (!strcmp(keyString, "KEY_HOMEPAGE") return KEY_HOMEPAGE;
    else if (!strcmp(keyString, "HOMEPAGE"    ) return KEY_HOMEPAGE;
    else if (!strcmp(keyString, "KEY_REFRESH") return KEY_REFRESH;
    else if (!strcmp(keyString, "REFRESH"    ) return KEY_REFRESH;
    else if (!strcmp(keyString, "KEY_EXIT") return KEY_EXIT;
    else if (!strcmp(keyString, "EXIT"    ) return KEY_EXIT;
    else if (!strcmp(keyString, "KEY_MOVE") return KEY_MOVE;
    else if (!strcmp(keyString, "MOVE"    ) return KEY_MOVE;
    else if (!strcmp(keyString, "KEY_EDIT") return KEY_EDIT;
    else if (!strcmp(keyString, "EDIT"    ) return KEY_EDIT;
    else if (!strcmp(keyString, "KEY_SCROLLUP") return KEY_SCROLLUP;
    else if (!strcmp(keyString, "SCROLLUP"    ) return KEY_SCROLLUP;
    else if (!strcmp(keyString, "KEY_SCROLLDOWN") return KEY_SCROLLDOWN;
    else if (!strcmp(keyString, "SCROLLDOWN"    ) return KEY_SCROLLDOWN;
    else if (!strcmp(keyString, "KEY_KPLEFTPAREN") return KEY_KPLEFTPAREN;
    else if (!strcmp(keyString, "KPLEFTPAREN"    ) return KEY_KPLEFTPAREN;
    else if (!strcmp(keyString, "KEY_KPRIGHTPAREN") return KEY_KPRIGHTPAREN;
    else if (!strcmp(keyString, "KPRIGHTPAREN"    ) return KEY_KPRIGHTPAREN;
    else if (!strcmp(keyString, "KEY_NEW") return KEY_NEW;
    else if (!strcmp(keyString, "NEW"    ) return KEY_NEW;
    else if (!strcmp(keyString, "KEY_REDO") return KEY_REDO;
    else if (!strcmp(keyString, "REDO"    ) return KEY_REDO;
    else if (!strcmp(keyString, "KEY_F13") return KEY_F13;
    else if (!strcmp(keyString, "F13"    ) return KEY_F13;
    else if (!strcmp(keyString, "KEY_F14") return KEY_F14;
    else if (!strcmp(keyString, "F14"    ) return KEY_F14;
    else if (!strcmp(keyString, "KEY_F15") return KEY_F15;
    else if (!strcmp(keyString, "F15"    ) return KEY_F15;
    else if (!strcmp(keyString, "KEY_F16") return KEY_F16;
    else if (!strcmp(keyString, "F16"    ) return KEY_F16;
    else if (!strcmp(keyString, "KEY_F17") return KEY_F17;
    else if (!strcmp(keyString, "F17"    ) return KEY_F17;
    else if (!strcmp(keyString, "KEY_F18") return KEY_F18;
    else if (!strcmp(keyString, "F18"    ) return KEY_F18;
    else if (!strcmp(keyString, "KEY_F19") return KEY_F19;
    else if (!strcmp(keyString, "F19"    ) return KEY_F19;
    else if (!strcmp(keyString, "KEY_F20") return KEY_F20;
    else if (!strcmp(keyString, "F20"    ) return KEY_F20;
    else if (!strcmp(keyString, "KEY_F21") return KEY_F21;
    else if (!strcmp(keyString, "F21"    ) return KEY_F21;
    else if (!strcmp(keyString, "KEY_F22") return KEY_F22;
    else if (!strcmp(keyString, "F22"    ) return KEY_F22;
    else if (!strcmp(keyString, "KEY_F23") return KEY_F23;
    else if (!strcmp(keyString, "F23"    ) return KEY_F23;
    else if (!strcmp(keyString, "KEY_F24") return KEY_F24;
    else if (!strcmp(keyString, "F24"    ) return KEY_F24;
    else if (!strcmp(keyString, "KEY_PLAYCD") return KEY_PLAYCD;
    else if (!strcmp(keyString, "PLAYCD"    ) return KEY_PLAYCD;
    else if (!strcmp(keyString, "KEY_PAUSECD") return KEY_PAUSECD;
    else if (!strcmp(keyString, "PAUSECD"    ) return KEY_PAUSECD;
    else if (!strcmp(keyString, "KEY_PROG3") return KEY_PROG3;
    else if (!strcmp(keyString, "PROG3"    ) return KEY_PROG3;
    else if (!strcmp(keyString, "KEY_PROG4") return KEY_PROG4;
    else if (!strcmp(keyString, "PROG4"    ) return KEY_PROG4;
    else if (!strcmp(keyString, "KEY_DASHBOARD") return KEY_DASHBOARD;
    else if (!strcmp(keyString, "DASHBOARD"    ) return KEY_DASHBOARD;
    else if (!strcmp(keyString, "KEY_SUSPEND") return KEY_SUSPEND;
    else if (!strcmp(keyString, "SUSPEND"    ) return KEY_SUSPEND;
    else if (!strcmp(keyString, "KEY_CLOSE") return KEY_CLOSE;
    else if (!strcmp(keyString, "CLOSE"    ) return KEY_CLOSE;
    else if (!strcmp(keyString, "KEY_PLAY") return KEY_PLAY;
    else if (!strcmp(keyString, "PLAY"    ) return KEY_PLAY;
    else if (!strcmp(keyString, "KEY_FASTFORWARD") return KEY_FASTFORWARD;
    else if (!strcmp(keyString, "FASTFORWARD"    ) return KEY_FASTFORWARD;
    else if (!strcmp(keyString, "KEY_BASSBOOST") return KEY_BASSBOOST;
    else if (!strcmp(keyString, "BASSBOOST"    ) return KEY_BASSBOOST;
    else if (!strcmp(keyString, "KEY_PRINT") return KEY_PRINT;
    else if (!strcmp(keyString, "PRINT"    ) return KEY_PRINT;
    else if (!strcmp(keyString, "KEY_HP") return KEY_HP;
    else if (!strcmp(keyString, "HP"    ) return KEY_HP;
    else if (!strcmp(keyString, "KEY_CAMERA") return KEY_CAMERA;
    else if (!strcmp(keyString, "CAMERA"    ) return KEY_CAMERA;
    else if (!strcmp(keyString, "KEY_SOUND") return KEY_SOUND;
    else if (!strcmp(keyString, "SOUND"    ) return KEY_SOUND;
    else if (!strcmp(keyString, "KEY_QUESTION") return KEY_QUESTION;
    else if (!strcmp(keyString, "QUESTION"    ) return KEY_QUESTION;
    else if (!strcmp(keyString, "KEY_EMAIL") return KEY_EMAIL;
    else if (!strcmp(keyString, "EMAIL"    ) return KEY_EMAIL;
    else if (!strcmp(keyString, "KEY_CHAT") return KEY_CHAT;
    else if (!strcmp(keyString, "CHAT"    ) return KEY_CHAT;
    else if (!strcmp(keyString, "KEY_SEARCH") return KEY_SEARCH;
    else if (!strcmp(keyString, "SEARCH"    ) return KEY_SEARCH;
    else if (!strcmp(keyString, "KEY_CONNECT") return KEY_CONNECT;
    else if (!strcmp(keyString, "CONNECT"    ) return KEY_CONNECT;
    else if (!strcmp(keyString, "KEY_FINANCE") return KEY_FINANCE;
    else if (!strcmp(keyString, "FINANCE"    ) return KEY_FINANCE;
    else if (!strcmp(keyString, "KEY_SPORT") return KEY_SPORT;
    else if (!strcmp(keyString, "SPORT"    ) return KEY_SPORT;
    else if (!strcmp(keyString, "KEY_SHOP") return KEY_SHOP;
    else if (!strcmp(keyString, "SHOP"    ) return KEY_SHOP;
    else if (!strcmp(keyString, "KEY_ALTERASE") return KEY_ALTERASE;
    else if (!strcmp(keyString, "ALTERASE"    ) return KEY_ALTERASE;
    else if (!strcmp(keyString, "KEY_CANCEL") return KEY_CANCEL;
    else if (!strcmp(keyString, "CANCEL"    ) return KEY_CANCEL;
    else if (!strcmp(keyString, "KEY_BRIGHTNESSDOWN") return KEY_BRIGHTNESSDOWN;
    else if (!strcmp(keyString, "BRIGHTNESSDOWN"    ) return KEY_BRIGHTNESSDOWN;
    else if (!strcmp(keyString, "KEY_BRIGHTNESSUP") return KEY_BRIGHTNESSUP;
    else if (!strcmp(keyString, "BRIGHTNESSUP"    ) return KEY_BRIGHTNESSUP;
    else if (!strcmp(keyString, "KEY_MEDIA") return KEY_MEDIA;
    else if (!strcmp(keyString, "MEDIA"    ) return KEY_MEDIA;
    else if (!strcmp(keyString, "KEY_SWITCHVIDEOMODE") return KEY_SWITCHVIDEOMODE;
    else if (!strcmp(keyString, "SWITCHVIDEOMODE"    ) return KEY_SWITCHVIDEOMODE;
    else if (!strcmp(keyString, "KEY_KBDILLUMTOGGLE") return KEY_KBDILLUMTOGGLE;
    else if (!strcmp(keyString, "KBDILLUMTOGGLE"    ) return KEY_KBDILLUMTOGGLE;
    else if (!strcmp(keyString, "KEY_KBDILLUMDOWN") return KEY_KBDILLUMDOWN;
    else if (!strcmp(keyString, "KBDILLUMDOWN"    ) return KEY_KBDILLUMDOWN;
    else if (!strcmp(keyString, "KEY_KBDILLUMUP") return KEY_KBDILLUMUP;
    else if (!strcmp(keyString, "KBDILLUMUP"    ) return KEY_KBDILLUMUP;
    else if (!strcmp(keyString, "KEY_SEND") return KEY_SEND;
    else if (!strcmp(keyString, "SEND"    ) return KEY_SEND;
    else if (!strcmp(keyString, "KEY_REPLY") return KEY_REPLY;
    else if (!strcmp(keyString, "REPLY"    ) return KEY_REPLY;
    else if (!strcmp(keyString, "KEY_FORWARDMAIL") return KEY_FORWARDMAIL;
    else if (!strcmp(keyString, "FORWARDMAIL"    ) return KEY_FORWARDMAIL;
    else if (!strcmp(keyString, "KEY_SAVE") return KEY_SAVE;
    else if (!strcmp(keyString, "SAVE"    ) return KEY_SAVE;
    else if (!strcmp(keyString, "KEY_DOCUMENTS") return KEY_DOCUMENTS;
    else if (!strcmp(keyString, "DOCUMENTS"    ) return KEY_DOCUMENTS;
    else if (!strcmp(keyString, "KEY_BATTERY") return KEY_BATTERY;
    else if (!strcmp(keyString, "BATTERY"    ) return KEY_BATTERY;
    else if (!strcmp(keyString, "KEY_BLUETOOTH") return KEY_BLUETOOTH;
    else if (!strcmp(keyString, "BLUETOOTH"    ) return KEY_BLUETOOTH;
    else if (!strcmp(keyString, "KEY_WLAN") return KEY_WLAN;
    else if (!strcmp(keyString, "WLAN"    ) return KEY_WLAN;
    else if (!strcmp(keyString, "KEY_UWB") return KEY_UWB;
    else if (!strcmp(keyString, "UWB"    ) return KEY_UWB;
    else if (!strcmp(keyString, "KEY_UNKNOWN") return KEY_UNKNOWN;
    else if (!strcmp(keyString, "UNKNOWN"    ) return KEY_UNKNOWN;
    else if (!strcmp(keyString, "KEY_VIDEO_NEXT") return KEY_VIDEO_NEXT;
    else if (!strcmp(keyString, "VIDEO_NEXT"    ) return KEY_VIDEO_NEXT;
    else if (!strcmp(keyString, "KEY_VIDEO_PREV") return KEY_VIDEO_PREV;
    else if (!strcmp(keyString, "VIDEO_PREV"    ) return KEY_VIDEO_PREV;
    else if (!strcmp(keyString, "KEY_BRIGHTNESS_CYCLE") return KEY_BRIGHTNESS_CYCLE;
    else if (!strcmp(keyString, "BRIGHTNESS_CYCLE"    ) return KEY_BRIGHTNESS_CYCLE;
    else if (!strcmp(keyString, "KEY_BRIGHTNESS_AUTO") return KEY_BRIGHTNESS_AUTO;
    else if (!strcmp(keyString, "BRIGHTNESS_AUTO"    ) return KEY_BRIGHTNESS_AUTO;
    else if (!strcmp(keyString, "KEY_BRIGHTNESS_ZERO") return KEY_BRIGHTNESS_ZERO;
    else if (!strcmp(keyString, "BRIGHTNESS_ZERO"    ) return KEY_BRIGHTNESS_ZERO;
    else if (!strcmp(keyString, "KEY_DISPLAY_OFF") return KEY_DISPLAY_OFF;
    else if (!strcmp(keyString, "DISPLAY_OFF"    ) return KEY_DISPLAY_OFF;
    else if (!strcmp(keyString, "KEY_WWAN") return KEY_WWAN;
    else if (!strcmp(keyString, "WWAN"    ) return KEY_WWAN;
    else if (!strcmp(keyString, "KEY_WIMAX") return KEY_WIMAX;
    else if (!strcmp(keyString, "WIMAX"    ) return KEY_WIMAX;
    else if (!strcmp(keyString, "KEY_RFKILL") return KEY_RFKILL;
    else if (!strcmp(keyString, "RFKILL"    ) return KEY_RFKILL;
    else if (!strcmp(keyString, "KEY_MICMUTE") return KEY_MICMUTE;
    else if (!strcmp(keyString, "MICMUTE"    ) return KEY_MICMUTE;
    else if (strcmp(keyString, "BTN_MISC") == 0) return BTN_MISC;
    else if (strcmp(keyString, "BTN_0") == 0) return BTN_0;
    else if (strcmp(keyString, "BTN_1") == 0) return BTN_1;
    else if (strcmp(keyString, "BTN_2") == 0) return BTN_2;
    else if (strcmp(keyString, "BTN_3") == 0) return BTN_3;
    else if (strcmp(keyString, "BTN_4") == 0) return BTN_4;
    else if (strcmp(keyString, "BTN_5") == 0) return BTN_5;
    else if (strcmp(keyString, "BTN_6") == 0) return BTN_6;
    else if (strcmp(keyString, "BTN_7") == 0) return BTN_7;
    else if (strcmp(keyString, "BTN_8") == 0) return BTN_8;
    else if (strcmp(keyString, "BTN_9") == 0) return BTN_9;
    else if (strcmp(keyString, "BTN_MOUSE") == 0) return BTN_MOUSE;
    else if (strcmp(keyString, "BTN_LEFT") == 0) return BTN_LEFT;
    else if (strcmp(keyString, "BTN_RIGHT") == 0) return BTN_RIGHT;
    else if (strcmp(keyString, "BTN_MIDDLE") == 0) return BTN_MIDDLE;
    else if (strcmp(keyString, "BTN_SIDE") == 0) return BTN_SIDE;
    else if (strcmp(keyString, "BTN_EXTRA") == 0) return BTN_EXTRA;
    else if (strcmp(keyString, "BTN_FORWARD") == 0) return BTN_FORWARD;
    else if (strcmp(keyString, "BTN_BACK") == 0) return BTN_BACK;
    else if (strcmp(keyString, "BTN_TASK") == 0) return BTN_TASK;
    else if (strcmp(keyString, "BTN_JOYSTICK") == 0) return BTN_JOYSTICK;
    else if (strcmp(keyString, "BTN_TRIGGER") == 0) return BTN_TRIGGER;
    else if (strcmp(keyString, "BTN_THUMB") == 0) return BTN_THUMB;
    else if (strcmp(keyString, "BTN_THUMB2") == 0) return BTN_THUMB2;
    else if (strcmp(keyString, "BTN_TOP") == 0) return BTN_TOP;
    else if (strcmp(keyString, "BTN_TOP2") == 0) return BTN_TOP2;
    else if (strcmp(keyString, "BTN_PINKIE") == 0) return BTN_PINKIE;
    else if (strcmp(keyString, "BTN_BASE") == 0) return BTN_BASE;
    else if (strcmp(keyString, "BTN_BASE2") == 0) return BTN_BASE2;
    else if (strcmp(keyString, "BTN_BASE3") == 0) return BTN_BASE3;
    else if (strcmp(keyString, "BTN_BASE4") == 0) return BTN_BASE4;
    else if (strcmp(keyString, "BTN_BASE5") == 0) return BTN_BASE5;
    else if (strcmp(keyString, "BTN_BASE6") == 0) return BTN_BASE6;
    else if (strcmp(keyString, "BTN_DEAD") == 0) return BTN_DEAD;
    else if (strcmp(keyString, "BTN_GAMEPAD") == 0) return BTN_GAMEPAD;
    else if (strcmp(keyString, "BTN_SOUTH") == 0) return BTN_SOUTH;
    else if (strcmp(keyString, "BTN_A") == 0) return BTN_A;
    else if (strcmp(keyString, "BTN_EAST") == 0) return BTN_EAST;
    else if (strcmp(keyString, "BTN_B") == 0) return BTN_B;
    else if (strcmp(keyString, "BTN_C") == 0) return BTN_C;
    else if (strcmp(keyString, "BTN_NORTH") == 0) return BTN_NORTH;
    else if (strcmp(keyString, "BTN_X") == 0) return BTN_X;
    else if (strcmp(keyString, "BTN_WEST") == 0) return BTN_WEST;
    else if (strcmp(keyString, "BTN_Y") == 0) return BTN_Y;
    else if (strcmp(keyString, "BTN_Z") == 0) return BTN_Z;
    else if (strcmp(keyString, "BTN_TL") == 0) return BTN_TL;
    else if (strcmp(keyString, "BTN_TR") == 0) return BTN_TR;
    else if (strcmp(keyString, "BTN_TL2") == 0) return BTN_TL2;
    else if (strcmp(keyString, "BTN_TR2") == 0) return BTN_TR2;
    else if (strcmp(keyString, "BTN_SELECT") == 0) return BTN_SELECT;
    else if (strcmp(keyString, "BTN_START") == 0) return BTN_START;
    else if (strcmp(keyString, "BTN_MODE") == 0) return BTN_MODE;
    else if (strcmp(keyString, "BTN_THUMBL") == 0) return BTN_THUMBL;
    else if (strcmp(keyString, "BTN_THUMBR") == 0) return BTN_THUMBR;
    else if (strcmp(keyString, "BTN_DIGI") == 0) return BTN_DIGI;
    else if (strcmp(keyString, "BTN_TOOL_PEN") == 0) return BTN_TOOL_PEN;
    else if (strcmp(keyString, "BTN_TOOL_RUBBER") == 0) return BTN_TOOL_RUBBER;
    else if (strcmp(keyString, "BTN_TOOL_BRUSH") == 0) return BTN_TOOL_BRUSH;
    else if (strcmp(keyString, "BTN_TOOL_PENCIL") == 0) return BTN_TOOL_PENCIL;
    else if (strcmp(keyString, "BTN_TOOL_AIRBRUSH") == 0) return BTN_TOOL_AIRBRUSH;
    else if (strcmp(keyString, "BTN_TOOL_FINGER") == 0) return BTN_TOOL_FINGER;
    else if (strcmp(keyString, "BTN_TOOL_MOUSE") == 0) return BTN_TOOL_MOUSE;
    else if (strcmp(keyString, "BTN_TOOL_LENS") == 0) return BTN_TOOL_LENS;
    else if (strcmp(keyString, "BTN_TOOL_QUINTTAP") == 0) return BTN_TOOL_QUINTTAP;
    else if (strcmp(keyString, "BTN_STYLUS3") == 0) return BTN_STYLUS3;
    else if (strcmp(keyString, "BTN_TOUCH") == 0) return BTN_TOUCH;
    else if (strcmp(keyString, "BTN_STYLUS") == 0) return BTN_STYLUS;
    else if (strcmp(keyString, "BTN_STYLUS2") == 0) return BTN_STYLUS2;
    else if (strcmp(keyString, "BTN_TOOL_DOUBLETAP") == 0) return BTN_TOOL_DOUBLETAP;
    else if (strcmp(keyString, "BTN_TOOL_TRIPLETAP") == 0) return BTN_TOOL_TRIPLETAP;
    else if (strcmp(keyString, "BTN_TOOL_QUADTAP") == 0) return BTN_TOOL_QUADTAP;
    else if (strcmp(keyString, "BTN_WHEEL") == 0) return BTN_WHEEL;
    else if (strcmp(keyString, "BTN_GEAR_DOWN") == 0) return BTN_GEAR_DOWN;
    else if (strcmp(keyString, "BTN_GEAR_UP") == 0) return BTN_GEAR_UP;
    else if (!strcmp(keyString, "KEY_OK") return KEY_OK;
    else if (!strcmp(keyString, "OK"    ) return KEY_OK;
    else if (!strcmp(keyString, "KEY_SELECT") return KEY_SELECT;
    else if (!strcmp(keyString, "SELECT"    ) return KEY_SELECT;
    else if (!strcmp(keyString, "KEY_GOTO") return KEY_GOTO;
    else if (!strcmp(keyString, "GOTO"    ) return KEY_GOTO;
    else if (!strcmp(keyString, "KEY_CLEAR") return KEY_CLEAR;
    else if (!strcmp(keyString, "CLEAR"    ) return KEY_CLEAR;
    else if (!strcmp(keyString, "KEY_POWER2") return KEY_POWER2;
    else if (!strcmp(keyString, "POWER2"    ) return KEY_POWER2;
    else if (!strcmp(keyString, "KEY_OPTION") return KEY_OPTION;
    else if (!strcmp(keyString, "OPTION"    ) return KEY_OPTION;
    else if (!strcmp(keyString, "KEY_INFO") return KEY_INFO;
    else if (!strcmp(keyString, "INFO"    ) return KEY_INFO;
    else if (!strcmp(keyString, "KEY_TIME") return KEY_TIME;
    else if (!strcmp(keyString, "TIME"    ) return KEY_TIME;
    else if (!strcmp(keyString, "KEY_VENDOR") return KEY_VENDOR;
    else if (!strcmp(keyString, "VENDOR"    ) return KEY_VENDOR;
    else if (!strcmp(keyString, "KEY_ARCHIVE") return KEY_ARCHIVE;
    else if (!strcmp(keyString, "ARCHIVE"    ) return KEY_ARCHIVE;
    else if (!strcmp(keyString, "KEY_PROGRAM") return KEY_PROGRAM;
    else if (!strcmp(keyString, "PROGRAM"    ) return KEY_PROGRAM;
    else if (!strcmp(keyString, "KEY_CHANNEL") return KEY_CHANNEL;
    else if (!strcmp(keyString, "CHANNEL"    ) return KEY_CHANNEL;
    else if (!strcmp(keyString, "KEY_FAVORITES") return KEY_FAVORITES;
    else if (!strcmp(keyString, "FAVORITES"    ) return KEY_FAVORITES;
    else if (!strcmp(keyString, "KEY_EPG") return KEY_EPG;
    else if (!strcmp(keyString, "EPG"    ) return KEY_EPG;
    else if (!strcmp(keyString, "KEY_PVR") return KEY_PVR;
    else if (!strcmp(keyString, "PVR"    ) return KEY_PVR;
    else if (!strcmp(keyString, "KEY_MHP") return KEY_MHP;
    else if (!strcmp(keyString, "MHP"    ) return KEY_MHP;
    else if (!strcmp(keyString, "KEY_LANGUAGE") return KEY_LANGUAGE;
    else if (!strcmp(keyString, "LANGUAGE"    ) return KEY_LANGUAGE;
    else if (!strcmp(keyString, "KEY_TITLE") return KEY_TITLE;
    else if (!strcmp(keyString, "TITLE"    ) return KEY_TITLE;
    else if (!strcmp(keyString, "KEY_SUBTITLE") return KEY_SUBTITLE;
    else if (!strcmp(keyString, "SUBTITLE"    ) return KEY_SUBTITLE;
    else if (!strcmp(keyString, "KEY_ANGLE") return KEY_ANGLE;
    else if (!strcmp(keyString, "ANGLE"    ) return KEY_ANGLE;
    else if (!strcmp(keyString, "KEY_FULL_SCREEN") return KEY_FULL_SCREEN;
    else if (!strcmp(keyString, "FULL_SCREEN"    ) return KEY_FULL_SCREEN;
    else if (!strcmp(keyString, "KEY_ZOOM") return KEY_ZOOM;
    else if (!strcmp(keyString, "ZOOM"    ) return KEY_ZOOM;
    else if (!strcmp(keyString, "KEY_MODE") return KEY_MODE;
    else if (!strcmp(keyString, "MODE"    ) return KEY_MODE;
    else if (!strcmp(keyString, "KEY_KEYBOARD") return KEY_KEYBOARD;
    else if (!strcmp(keyString, "KEYBOARD"    ) return KEY_KEYBOARD;
    else if (!strcmp(keyString, "KEY_ASPECT_RATIO") return KEY_ASPECT_RATIO;
    else if (!strcmp(keyString, "ASPECT_RATIO"    ) return KEY_ASPECT_RATIO;
    else if (!strcmp(keyString, "KEY_SCREEN") return KEY_SCREEN;
    else if (!strcmp(keyString, "SCREEN"    ) return KEY_SCREEN;
    else if (!strcmp(keyString, "KEY_PC") return KEY_PC;
    else if (!strcmp(keyString, "PC"    ) return KEY_PC;
    else if (!strcmp(keyString, "KEY_TV") return KEY_TV;
    else if (!strcmp(keyString, "TV"    ) return KEY_TV;
    else if (!strcmp(keyString, "KEY_TV2") return KEY_TV2;
    else if (!strcmp(keyString, "TV2"    ) return KEY_TV2;
    else if (!strcmp(keyString, "KEY_VCR") return KEY_VCR;
    else if (!strcmp(keyString, "VCR"    ) return KEY_VCR;
    else if (!strcmp(keyString, "KEY_VCR2") return KEY_VCR2;
    else if (!strcmp(keyString, "VCR2"    ) return KEY_VCR2;
    else if (!strcmp(keyString, "KEY_SAT") return KEY_SAT;
    else if (!strcmp(keyString, "SAT"    ) return KEY_SAT;
    else if (!strcmp(keyString, "KEY_SAT2") return KEY_SAT2;
    else if (!strcmp(keyString, "SAT2"    ) return KEY_SAT2;
    else if (!strcmp(keyString, "KEY_CD") return KEY_CD;
    else if (!strcmp(keyString, "CD"    ) return KEY_CD;
    else if (!strcmp(keyString, "KEY_TAPE") return KEY_TAPE;
    else if (!strcmp(keyString, "TAPE"    ) return KEY_TAPE;
    else if (!strcmp(keyString, "KEY_RADIO") return KEY_RADIO;
    else if (!strcmp(keyString, "RADIO"    ) return KEY_RADIO;
    else if (!strcmp(keyString, "KEY_TUNER") return KEY_TUNER;
    else if (!strcmp(keyString, "TUNER"    ) return KEY_TUNER;
    else if (!strcmp(keyString, "KEY_PLAYER") return KEY_PLAYER;
    else if (!strcmp(keyString, "PLAYER"    ) return KEY_PLAYER;
    else if (!strcmp(keyString, "KEY_TEXT") return KEY_TEXT;
    else if (!strcmp(keyString, "TEXT"    ) return KEY_TEXT;
    else if (!strcmp(keyString, "KEY_DVD") return KEY_DVD;
    else if (!strcmp(keyString, "DVD"    ) return KEY_DVD;
    else if (!strcmp(keyString, "KEY_AUX") return KEY_AUX;
    else if (!strcmp(keyString, "AUX"    ) return KEY_AUX;
    else if (!strcmp(keyString, "KEY_MP3") return KEY_MP3;
    else if (!strcmp(keyString, "MP3"    ) return KEY_MP3;
    else if (!strcmp(keyString, "KEY_AUDIO") return KEY_AUDIO;
    else if (!strcmp(keyString, "AUDIO"    ) return KEY_AUDIO;
    else if (!strcmp(keyString, "KEY_VIDEO") return KEY_VIDEO;
    else if (!strcmp(keyString, "VIDEO"    ) return KEY_VIDEO;
    else if (!strcmp(keyString, "KEY_DIRECTORY") return KEY_DIRECTORY;
    else if (!strcmp(keyString, "DIRECTORY"    ) return KEY_DIRECTORY;
    else if (!strcmp(keyString, "KEY_LIST") return KEY_LIST;
    else if (!strcmp(keyString, "LIST"    ) return KEY_LIST;
    else if (!strcmp(keyString, "KEY_MEMO") return KEY_MEMO;
    else if (!strcmp(keyString, "MEMO"    ) return KEY_MEMO;
    else if (!strcmp(keyString, "KEY_CALENDAR") return KEY_CALENDAR;
    else if (!strcmp(keyString, "CALENDAR"    ) return KEY_CALENDAR;
    else if (!strcmp(keyString, "KEY_RED") return KEY_RED;
    else if (!strcmp(keyString, "RED"    ) return KEY_RED;
    else if (!strcmp(keyString, "KEY_GREEN") return KEY_GREEN;
    else if (!strcmp(keyString, "GREEN"    ) return KEY_GREEN;
    else if (!strcmp(keyString, "KEY_YELLOW") return KEY_YELLOW;
    else if (!strcmp(keyString, "YELLOW"    ) return KEY_YELLOW;
    else if (!strcmp(keyString, "KEY_BLUE") return KEY_BLUE;
    else if (!strcmp(keyString, "BLUE"    ) return KEY_BLUE;
    else if (!strcmp(keyString, "KEY_CHANNELUP") return KEY_CHANNELUP;
    else if (!strcmp(keyString, "CHANNELUP"    ) return KEY_CHANNELUP;
    else if (!strcmp(keyString, "KEY_CHANNELDOWN") return KEY_CHANNELDOWN;
    else if (!strcmp(keyString, "CHANNELDOWN"    ) return KEY_CHANNELDOWN;
    else if (!strcmp(keyString, "KEY_FIRST") return KEY_FIRST;
    else if (!strcmp(keyString, "FIRST"    ) return KEY_FIRST;
    else if (!strcmp(keyString, "KEY_LAST") return KEY_LAST;
    else if (!strcmp(keyString, "LAST"    ) return KEY_LAST;
    else if (!strcmp(keyString, "KEY_AB") return KEY_AB;
    else if (!strcmp(keyString, "AB"    ) return KEY_AB;
    else if (!strcmp(keyString, "KEY_NEXT") return KEY_NEXT;
    else if (!strcmp(keyString, "NEXT"    ) return KEY_NEXT;
    else if (!strcmp(keyString, "KEY_RESTART") return KEY_RESTART;
    else if (!strcmp(keyString, "RESTART"    ) return KEY_RESTART;
    else if (!strcmp(keyString, "KEY_SLOW") return KEY_SLOW;
    else if (!strcmp(keyString, "SLOW"    ) return KEY_SLOW;
    else if (!strcmp(keyString, "KEY_SHUFFLE") return KEY_SHUFFLE;
    else if (!strcmp(keyString, "SHUFFLE"    ) return KEY_SHUFFLE;
    else if (!strcmp(keyString, "KEY_BREAK") return KEY_BREAK;
    else if (!strcmp(keyString, "BREAK"    ) return KEY_BREAK;
    else if (!strcmp(keyString, "KEY_PREVIOUS") return KEY_PREVIOUS;
    else if (!strcmp(keyString, "PREVIOUS"    ) return KEY_PREVIOUS;
    else if (!strcmp(keyString, "KEY_DIGITS") return KEY_DIGITS;
    else if (!strcmp(keyString, "DIGITS"    ) return KEY_DIGITS;
    else if (!strcmp(keyString, "KEY_TEEN") return KEY_TEEN;
    else if (!strcmp(keyString, "TEEN"    ) return KEY_TEEN;
    else if (!strcmp(keyString, "KEY_TWEN") return KEY_TWEN;
    else if (!strcmp(keyString, "TWEN"    ) return KEY_TWEN;
    else if (!strcmp(keyString, "KEY_VIDEOPHONE") return KEY_VIDEOPHONE;
    else if (!strcmp(keyString, "VIDEOPHONE"    ) return KEY_VIDEOPHONE;
    else if (!strcmp(keyString, "KEY_GAMES") return KEY_GAMES;
    else if (!strcmp(keyString, "GAMES"    ) return KEY_GAMES;
    else if (!strcmp(keyString, "KEY_ZOOMIN") return KEY_ZOOMIN;
    else if (!strcmp(keyString, "ZOOMIN"    ) return KEY_ZOOMIN;
    else if (!strcmp(keyString, "KEY_ZOOMOUT") return KEY_ZOOMOUT;
    else if (!strcmp(keyString, "ZOOMOUT"    ) return KEY_ZOOMOUT;
    else if (!strcmp(keyString, "KEY_ZOOMRESET") return KEY_ZOOMRESET;
    else if (!strcmp(keyString, "ZOOMRESET"    ) return KEY_ZOOMRESET;
    else if (!strcmp(keyString, "KEY_WORDPROCESSOR") return KEY_WORDPROCESSOR;
    else if (!strcmp(keyString, "WORDPROCESSOR"    ) return KEY_WORDPROCESSOR;
    else if (!strcmp(keyString, "KEY_EDITOR") return KEY_EDITOR;
    else if (!strcmp(keyString, "EDITOR"    ) return KEY_EDITOR;
    else if (!strcmp(keyString, "KEY_SPREADSHEET") return KEY_SPREADSHEET;
    else if (!strcmp(keyString, "SPREADSHEET"    ) return KEY_SPREADSHEET;
    else if (!strcmp(keyString, "KEY_GRAPHICSEDITOR") return KEY_GRAPHICSEDITOR;
    else if (!strcmp(keyString, "GRAPHICSEDITOR"    ) return KEY_GRAPHICSEDITOR;
    else if (!strcmp(keyString, "KEY_PRESENTATION") return KEY_PRESENTATION;
    else if (!strcmp(keyString, "PRESENTATION"    ) return KEY_PRESENTATION;
    else if (!strcmp(keyString, "KEY_DATABASE") return KEY_DATABASE;
    else if (!strcmp(keyString, "DATABASE"    ) return KEY_DATABASE;
    else if (!strcmp(keyString, "KEY_NEWS") return KEY_NEWS;
    else if (!strcmp(keyString, "NEWS"    ) return KEY_NEWS;
    else if (!strcmp(keyString, "KEY_VOICEMAIL") return KEY_VOICEMAIL;
    else if (!strcmp(keyString, "VOICEMAIL"    ) return KEY_VOICEMAIL;
    else if (!strcmp(keyString, "KEY_ADDRESSBOOK") return KEY_ADDRESSBOOK;
    else if (!strcmp(keyString, "ADDRESSBOOK"    ) return KEY_ADDRESSBOOK;
    else if (!strcmp(keyString, "KEY_MESSENGER") return KEY_MESSENGER;
    else if (!strcmp(keyString, "MESSENGER"    ) return KEY_MESSENGER;
    else if (!strcmp(keyString, "KEY_DISPLAYTOGGLE") return KEY_DISPLAYTOGGLE;
    else if (!strcmp(keyString, "DISPLAYTOGGLE"    ) return KEY_DISPLAYTOGGLE;
    else if (!strcmp(keyString, "KEY_BRIGHTNESS_TOGGLE") return KEY_BRIGHTNESS_TOGGLE;
    else if (!strcmp(keyString, "BRIGHTNESS_TOGGLE"    ) return KEY_BRIGHTNESS_TOGGLE;
    else if (!strcmp(keyString, "KEY_SPELLCHECK") return KEY_SPELLCHECK;
    else if (!strcmp(keyString, "SPELLCHECK"    ) return KEY_SPELLCHECK;
    else if (!strcmp(keyString, "KEY_LOGOFF") return KEY_LOGOFF;
    else if (!strcmp(keyString, "LOGOFF"    ) return KEY_LOGOFF;
    else if (!strcmp(keyString, "KEY_DOLLAR") return KEY_DOLLAR;
    else if (!strcmp(keyString, "DOLLAR"    ) return KEY_DOLLAR;
    else if (!strcmp(keyString, "KEY_EURO") return KEY_EURO;
    else if (!strcmp(keyString, "EURO"    ) return KEY_EURO;
    else if (!strcmp(keyString, "KEY_FRAMEBACK") return KEY_FRAMEBACK;
    else if (!strcmp(keyString, "FRAMEBACK"    ) return KEY_FRAMEBACK;
    else if (!strcmp(keyString, "KEY_FRAMEFORWARD") return KEY_FRAMEFORWARD;
    else if (!strcmp(keyString, "FRAMEFORWARD"    ) return KEY_FRAMEFORWARD;
    else if (!strcmp(keyString, "KEY_CONTEXT_MENU") return KEY_CONTEXT_MENU;
    else if (!strcmp(keyString, "CONTEXT_MENU"    ) return KEY_CONTEXT_MENU;
    else if (!strcmp(keyString, "KEY_MEDIA_REPEAT") return KEY_MEDIA_REPEAT;
    else if (!strcmp(keyString, "MEDIA_REPEAT"    ) return KEY_MEDIA_REPEAT;
    else if (!strcmp(keyString, "KEY_10CHANNELSUP") return KEY_10CHANNELSUP;
    else if (!strcmp(keyString, "10CHANNELSUP"    ) return KEY_10CHANNELSUP;
    else if (!strcmp(keyString, "KEY_10CHANNELSDOWN") return KEY_10CHANNELSDOWN;
    else if (!strcmp(keyString, "10CHANNELSDOWN"    ) return KEY_10CHANNELSDOWN;
    else if (!strcmp(keyString, "KEY_IMAGES") return KEY_IMAGES;
    else if (!strcmp(keyString, "IMAGES"    ) return KEY_IMAGES;
    else if (!strcmp(keyString, "KEY_NOTIFICATION_CENTER") return KEY_NOTIFICATION_CENTER;
    else if (!strcmp(keyString, "NOTIFICATION_CENTER"    ) return KEY_NOTIFICATION_CENTER;
    else if (!strcmp(keyString, "KEY_PICKUP_PHONE") return KEY_PICKUP_PHONE;
    else if (!strcmp(keyString, "PICKUP_PHONE"    ) return KEY_PICKUP_PHONE;
    else if (!strcmp(keyString, "KEY_HANGUP_PHONE") return KEY_HANGUP_PHONE;
    else if (!strcmp(keyString, "HANGUP_PHONE"    ) return KEY_HANGUP_PHONE;
    else if (!strcmp(keyString, "KEY_DEL_EOL") return KEY_DEL_EOL;
    else if (!strcmp(keyString, "DEL_EOL"    ) return KEY_DEL_EOL;
    else if (!strcmp(keyString, "KEY_DEL_EOS") return KEY_DEL_EOS;
    else if (!strcmp(keyString, "DEL_EOS"    ) return KEY_DEL_EOS;
    else if (!strcmp(keyString, "KEY_INS_LINE") return KEY_INS_LINE;
    else if (!strcmp(keyString, "INS_LINE"    ) return KEY_INS_LINE;
    else if (!strcmp(keyString, "KEY_DEL_LINE") return KEY_DEL_LINE;
    else if (!strcmp(keyString, "DEL_LINE"    ) return KEY_DEL_LINE;
    else if (!strcmp(keyString, "KEY_FN") return KEY_FN;
    else if (!strcmp(keyString, "FN"    ) return KEY_FN;
    else if (!strcmp(keyString, "KEY_FN_ESC") return KEY_FN_ESC;
    else if (!strcmp(keyString, "FN_ESC"    ) return KEY_FN_ESC;
    else if (!strcmp(keyString, "KEY_FN_F1") return KEY_FN_F1;
    else if (!strcmp(keyString, "FN_F1"    ) return KEY_FN_F1;
    else if (!strcmp(keyString, "KEY_FN_F2") return KEY_FN_F2;
    else if (!strcmp(keyString, "FN_F2"    ) return KEY_FN_F2;
    else if (!strcmp(keyString, "KEY_FN_F3") return KEY_FN_F3;
    else if (!strcmp(keyString, "FN_F3"    ) return KEY_FN_F3;
    else if (!strcmp(keyString, "KEY_FN_F4") return KEY_FN_F4;
    else if (!strcmp(keyString, "FN_F4"    ) return KEY_FN_F4;
    else if (!strcmp(keyString, "KEY_FN_F5") return KEY_FN_F5;
    else if (!strcmp(keyString, "FN_F5"    ) return KEY_FN_F5;
    else if (!strcmp(keyString, "KEY_FN_F6") return KEY_FN_F6;
    else if (!strcmp(keyString, "FN_F6"    ) return KEY_FN_F6;
    else if (!strcmp(keyString, "KEY_FN_F7") return KEY_FN_F7;
    else if (!strcmp(keyString, "FN_F7"    ) return KEY_FN_F7;
    else if (!strcmp(keyString, "KEY_FN_F8") return KEY_FN_F8;
    else if (!strcmp(keyString, "FN_F8"    ) return KEY_FN_F8;
    else if (!strcmp(keyString, "KEY_FN_F9") return KEY_FN_F9;
    else if (!strcmp(keyString, "FN_F9"    ) return KEY_FN_F9;
    else if (!strcmp(keyString, "KEY_FN_F10") return KEY_FN_F10;
    else if (!strcmp(keyString, "FN_F10"    ) return KEY_FN_F10;
    else if (!strcmp(keyString, "KEY_FN_F11") return KEY_FN_F11;
    else if (!strcmp(keyString, "FN_F11"    ) return KEY_FN_F11;
    else if (!strcmp(keyString, "KEY_FN_F12") return KEY_FN_F12;
    else if (!strcmp(keyString, "FN_F12"    ) return KEY_FN_F12;
    else if (!strcmp(keyString, "KEY_FN_1") return KEY_FN_1;
    else if (!strcmp(keyString, "FN_1"    ) return KEY_FN_1;
    else if (!strcmp(keyString, "KEY_FN_2") return KEY_FN_2;
    else if (!strcmp(keyString, "FN_2"    ) return KEY_FN_2;
    else if (!strcmp(keyString, "KEY_FN_D") return KEY_FN_D;
    else if (!strcmp(keyString, "FN_D"    ) return KEY_FN_D;
    else if (!strcmp(keyString, "KEY_FN_E") return KEY_FN_E;
    else if (!strcmp(keyString, "FN_E"    ) return KEY_FN_E;
    else if (!strcmp(keyString, "KEY_FN_F") return KEY_FN_F;
    else if (!strcmp(keyString, "FN_F"    ) return KEY_FN_F;
    else if (!strcmp(keyString, "KEY_FN_S") return KEY_FN_S;
    else if (!strcmp(keyString, "FN_S"    ) return KEY_FN_S;
    else if (!strcmp(keyString, "KEY_FN_B") return KEY_FN_B;
    else if (!strcmp(keyString, "FN_B"    ) return KEY_FN_B;
    else if (!strcmp(keyString, "KEY_FN_RIGHT_SHIFT") return KEY_FN_RIGHT_SHIFT;
    else if (!strcmp(keyString, "FN_RIGHT_SHIFT"    ) return KEY_FN_RIGHT_SHIFT;
    else if (!strcmp(keyString, "KEY_BRL_DOT1") return KEY_BRL_DOT1;
    else if (!strcmp(keyString, "BRL_DOT1"    ) return KEY_BRL_DOT1;
    else if (!strcmp(keyString, "KEY_BRL_DOT2") return KEY_BRL_DOT2;
    else if (!strcmp(keyString, "BRL_DOT2"    ) return KEY_BRL_DOT2;
    else if (!strcmp(keyString, "KEY_BRL_DOT3") return KEY_BRL_DOT3;
    else if (!strcmp(keyString, "BRL_DOT3"    ) return KEY_BRL_DOT3;
    else if (!strcmp(keyString, "KEY_BRL_DOT4") return KEY_BRL_DOT4;
    else if (!strcmp(keyString, "BRL_DOT4"    ) return KEY_BRL_DOT4;
    else if (!strcmp(keyString, "KEY_BRL_DOT5") return KEY_BRL_DOT5;
    else if (!strcmp(keyString, "BRL_DOT5"    ) return KEY_BRL_DOT5;
    else if (!strcmp(keyString, "KEY_BRL_DOT6") return KEY_BRL_DOT6;
    else if (!strcmp(keyString, "BRL_DOT6"    ) return KEY_BRL_DOT6;
    else if (!strcmp(keyString, "KEY_BRL_DOT7") return KEY_BRL_DOT7;
    else if (!strcmp(keyString, "BRL_DOT7"    ) return KEY_BRL_DOT7;
    else if (!strcmp(keyString, "KEY_BRL_DOT8") return KEY_BRL_DOT8;
    else if (!strcmp(keyString, "BRL_DOT8"    ) return KEY_BRL_DOT8;
    else if (!strcmp(keyString, "KEY_BRL_DOT9") return KEY_BRL_DOT9;
    else if (!strcmp(keyString, "BRL_DOT9"    ) return KEY_BRL_DOT9;
    else if (!strcmp(keyString, "KEY_BRL_DOT10") return KEY_BRL_DOT10;
    else if (!strcmp(keyString, "BRL_DOT10"    ) return KEY_BRL_DOT10;
    else if (!strcmp(keyString, "KEY_NUMERIC_0") return KEY_NUMERIC_0;
    else if (!strcmp(keyString, "NUMERIC_0"    ) return KEY_NUMERIC_0;
    else if (!strcmp(keyString, "KEY_NUMERIC_1") return KEY_NUMERIC_1;
    else if (!strcmp(keyString, "NUMERIC_1"    ) return KEY_NUMERIC_1;
    else if (!strcmp(keyString, "KEY_NUMERIC_2") return KEY_NUMERIC_2;
    else if (!strcmp(keyString, "NUMERIC_2"    ) return KEY_NUMERIC_2;
    else if (!strcmp(keyString, "KEY_NUMERIC_3") return KEY_NUMERIC_3;
    else if (!strcmp(keyString, "NUMERIC_3"    ) return KEY_NUMERIC_3;
    else if (!strcmp(keyString, "KEY_NUMERIC_4") return KEY_NUMERIC_4;
    else if (!strcmp(keyString, "NUMERIC_4"    ) return KEY_NUMERIC_4;
    else if (!strcmp(keyString, "KEY_NUMERIC_5") return KEY_NUMERIC_5;
    else if (!strcmp(keyString, "NUMERIC_5"    ) return KEY_NUMERIC_5;
    else if (!strcmp(keyString, "KEY_NUMERIC_6") return KEY_NUMERIC_6;
    else if (!strcmp(keyString, "NUMERIC_6"    ) return KEY_NUMERIC_6;
    else if (!strcmp(keyString, "KEY_NUMERIC_7") return KEY_NUMERIC_7;
    else if (!strcmp(keyString, "NUMERIC_7"    ) return KEY_NUMERIC_7;
    else if (!strcmp(keyString, "KEY_NUMERIC_8") return KEY_NUMERIC_8;
    else if (!strcmp(keyString, "NUMERIC_8"    ) return KEY_NUMERIC_8;
    else if (!strcmp(keyString, "KEY_NUMERIC_9") return KEY_NUMERIC_9;
    else if (!strcmp(keyString, "NUMERIC_9"    ) return KEY_NUMERIC_9;
    else if (!strcmp(keyString, "KEY_NUMERIC_STAR") return KEY_NUMERIC_STAR;
    else if (!strcmp(keyString, "NUMERIC_STAR"    ) return KEY_NUMERIC_STAR;
    else if (!strcmp(keyString, "KEY_NUMERIC_POUND") return KEY_NUMERIC_POUND;
    else if (!strcmp(keyString, "NUMERIC_POUND"    ) return KEY_NUMERIC_POUND;
    else if (!strcmp(keyString, "KEY_NUMERIC_A") return KEY_NUMERIC_A;
    else if (!strcmp(keyString, "NUMERIC_A"    ) return KEY_NUMERIC_A;
    else if (!strcmp(keyString, "KEY_NUMERIC_B") return KEY_NUMERIC_B;
    else if (!strcmp(keyString, "NUMERIC_B"    ) return KEY_NUMERIC_B;
    else if (!strcmp(keyString, "KEY_NUMERIC_C") return KEY_NUMERIC_C;
    else if (!strcmp(keyString, "NUMERIC_C"    ) return KEY_NUMERIC_C;
    else if (!strcmp(keyString, "KEY_NUMERIC_D") return KEY_NUMERIC_D;
    else if (!strcmp(keyString, "NUMERIC_D"    ) return KEY_NUMERIC_D;
    else if (!strcmp(keyString, "KEY_CAMERA_FOCUS") return KEY_CAMERA_FOCUS;
    else if (!strcmp(keyString, "CAMERA_FOCUS"    ) return KEY_CAMERA_FOCUS;
    else if (!strcmp(keyString, "KEY_WPS_BUTTON") return KEY_WPS_BUTTON;
    else if (!strcmp(keyString, "WPS_BUTTON"    ) return KEY_WPS_BUTTON;
    else if (!strcmp(keyString, "KEY_TOUCHPAD_TOGGLE") return KEY_TOUCHPAD_TOGGLE;
    else if (!strcmp(keyString, "TOUCHPAD_TOGGLE"    ) return KEY_TOUCHPAD_TOGGLE;
    else if (!strcmp(keyString, "KEY_TOUCHPAD_ON") return KEY_TOUCHPAD_ON;
    else if (!strcmp(keyString, "TOUCHPAD_ON"    ) return KEY_TOUCHPAD_ON;
    else if (!strcmp(keyString, "KEY_TOUCHPAD_OFF") return KEY_TOUCHPAD_OFF;
    else if (!strcmp(keyString, "TOUCHPAD_OFF"    ) return KEY_TOUCHPAD_OFF;
    else if (!strcmp(keyString, "KEY_CAMERA_ZOOMIN") return KEY_CAMERA_ZOOMIN;
    else if (!strcmp(keyString, "CAMERA_ZOOMIN"    ) return KEY_CAMERA_ZOOMIN;
    else if (!strcmp(keyString, "KEY_CAMERA_ZOOMOUT") return KEY_CAMERA_ZOOMOUT;
    else if (!strcmp(keyString, "CAMERA_ZOOMOUT"    ) return KEY_CAMERA_ZOOMOUT;
    else if (!strcmp(keyString, "KEY_CAMERA_UP") return KEY_CAMERA_UP;
    else if (!strcmp(keyString, "CAMERA_UP"    ) return KEY_CAMERA_UP;
    else if (!strcmp(keyString, "KEY_CAMERA_DOWN") return KEY_CAMERA_DOWN;
    else if (!strcmp(keyString, "CAMERA_DOWN"    ) return KEY_CAMERA_DOWN;
    else if (!strcmp(keyString, "KEY_CAMERA_LEFT") return KEY_CAMERA_LEFT;
    else if (!strcmp(keyString, "CAMERA_LEFT"    ) return KEY_CAMERA_LEFT;
    else if (!strcmp(keyString, "KEY_CAMERA_RIGHT") return KEY_CAMERA_RIGHT;
    else if (!strcmp(keyString, "CAMERA_RIGHT"    ) return KEY_CAMERA_RIGHT;
    else if (!strcmp(keyString, "KEY_ATTENDANT_ON") return KEY_ATTENDANT_ON;
    else if (!strcmp(keyString, "ATTENDANT_ON"    ) return KEY_ATTENDANT_ON;
    else if (!strcmp(keyString, "KEY_ATTENDANT_OFF") return KEY_ATTENDANT_OFF;
    else if (!strcmp(keyString, "ATTENDANT_OFF"    ) return KEY_ATTENDANT_OFF;
    else if (!strcmp(keyString, "KEY_ATTENDANT_TOGGLE") return KEY_ATTENDANT_TOGGLE;
    else if (!strcmp(keyString, "ATTENDANT_TOGGLE"    ) return KEY_ATTENDANT_TOGGLE;
    else if (!strcmp(keyString, "KEY_LIGHTS_TOGGLE") return KEY_LIGHTS_TOGGLE;
    else if (!strcmp(keyString, "LIGHTS_TOGGLE"    ) return KEY_LIGHTS_TOGGLE;
    else if (strcmp(keyString, "BTN_DPAD_UP") == 0) return BTN_DPAD_UP;
    else if (strcmp(keyString, "BTN_DPAD_DOWN") == 0) return BTN_DPAD_DOWN;
    else if (strcmp(keyString, "BTN_DPAD_LEFT") == 0) return BTN_DPAD_LEFT;
    else if (strcmp(keyString, "BTN_DPAD_RIGHT") == 0) return BTN_DPAD_RIGHT;
    else if (!strcmp(keyString, "KEY_ALS_TOGGLE") return KEY_ALS_TOGGLE;
    else if (!strcmp(keyString, "ALS_TOGGLE"    ) return KEY_ALS_TOGGLE;
    else if (!strcmp(keyString, "KEY_ROTATE_LOCK_TOGGLE") return KEY_ROTATE_LOCK_TOGGLE;
    else if (!strcmp(keyString, "ROTATE_LOCK_TOGGLE"    ) return KEY_ROTATE_LOCK_TOGGLE;
    else return 0;
}

/**
 * Checks if the event is key down.
 * Linux input sends value=2 for repeated key down.
 * We treat them as keydown events for processing.
 * */
int isDown(int value)
{
    return value == 1 || value == 2;
}

/**
 * Checks if the key is a keypad key.
 * */
int isKeypad(int code)
{
    switch (code)
    {
        case KEY_KPASTERISK:
        case KEY_KP7:
        case KEY_KP8:
        case KEY_KP9:
        case KEY_KPMINUS:
        case KEY_KP4:
        case KEY_KP5:
        case KEY_KP6:
        case KEY_KPPLUS:
        case KEY_KP1:
        case KEY_KP2:
        case KEY_KP3:
        case KEY_KP0:
        case KEY_KPDOT:
            {
                return 1;
            }
        default:
            {
                return 0;
            }
    }
}

/**
 * Checks if the key is a modifier key.
 * */
int isModifier(int code)
{
    switch (code)
    {
        case KEY_LEFTSHIFT:
        case KEY_RIGHTSHIFT:
        case KEY_LEFTCTRL:
        case KEY_RIGHTCTRL:
        case KEY_LEFTALT:
        case KEY_RIGHTALT:
        case KEY_LEFTMETA:
        case KEY_RIGHTMETA:
        case KEY_CAPSLOCK:
        case KEY_NUMLOCK:
        case KEY_SCROLLLOCK:
            {
                return 1;
            }
        default:
            {
                return 0;
            }
    }
}
